# Generated by Django 2.2 on 2019-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attractionsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('dataId', models.CharField(max_length=64)),
                ('theme', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('productStarLevel', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('intro', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=25)),
                ('preference', models.CharField(max_length=255)),
            ],
        ),
    ]
