# Generated by Django 2.2 on 2019-05-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userId',
        ),
    ]
