# Generated by Django 2.2 on 2019-05-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attractionsInfo',
            fields=[
                ('districts', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('dataid', models.CharField(db_column='dataId', max_length=64)),
                ('theme', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('productstarlevel', models.CharField(blank=True, db_column='productStarLevel', max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('countid', models.CharField(db_column='countId', max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userid', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('preference', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
