# Generated by Django 2.2 on 2019-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
