# Generated by Django 2.2 on 2019-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_auto_20190617_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
