# Generated by Django 2.2 on 2019-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_auto_20190617_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='preference',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tree',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
